COMPONENT_ADD_INCLUDEDIRS := modules/dotprod/include \
							modules/support/include \
							modules/windows/include \
							modules/windows/hann/include \
							modules/windows/blackman/include \
							modules/windows/blackman_harris/include \
							modules/windows/blackman_nuttall/include \
							modules/windows/nuttall/include \
							modules/windows/flat_top/include \
							modules/iir/include \
							modules/fir/include \
							modules/math/include \
							modules/math/add/include \
							modules/math/sub/include \
							modules/math/mul/include \
							modules/math/addc/include \
							modules/math/mulc/include \
							modules/math/sqrt/include \
							modules/matrix/add/include \
							modules/matrix/addc/include \
							modules/matrix/mul/include \
							modules/matrix/mulc/include \
							modules/matrix/sub/include \
							modules/matrix/include \
							modules/fft/include \
							modules/dct/include \
							modules/conv/include \
							modules/kalman/ekf/include \
							modules/kalman/ekf_imu13states/include \
							modules/common/include

COMPONENT_SRCDIRS :=. \
					modules/common \
					modules/common/misc \
					modules/dotprod \
					modules/dotprod/float \
					modules/dotprod/fixed \
					modules/matrix \
					modules/matrix/add \
					modules/matrix/add/float \
					modules/matrix/addc \
					modules/matrix/addc/float \
					modules/matrix/mul \
					modules/matrix/mul/float \
					modules/matrix/mul/fixed \
					modules/matrix/mulc \
					modules/matrix/mulc/float \
					modules/matrix/sub \
					modules/matrix/sub/float \
					modules/matrix/mat \
					modules/math \
					modules/math/mulc \
					modules/math/mulc/float \
					modules/math/mulc/fixed \
					modules/math/addc \
					modules/math/addc/float \
					modules/math/add \
					modules/math/add/float \
					modules/math/add/fixed \
					modules/math/mul \
					modules/math/mul/float \
					modules/math/mul/fixed \
					modules/math/sub \
					modules/math/sub/float \
					modules/math/sqrt/float \
					modules/fft/float \
					modules/fft/fixed \
					modules/support \
					modules/support/snr/float \
					modules/support/sfdr/float \
					modules/support/misc \
					modules/support/view \
					modules/windows/hann \
					modules/windows/hann/float \
					modules/windows/hann/fixed \
					modules/windows/blackman \
					modules/windows/blackman/float \
					modules/windows/blackman/fixed \
					modules/windows/blackman_harris \
					modules/windows/blackman_harris/float \
					modules/windows/blackman_harris/fixed \
					modules/windows/blackman_nuttall \
					modules/windows/blackman_nuttall/float \
					modules/windows/blackman_nuttall/fixed \
					modules/windows/nuttall \
					modules/windows/nuttall/float \
					modules/windows/nuttall/fixed \
					modules/windows/flat_top \
					modules/windows/flat_top/float \
					modules/windows/flat_top/fixed \
					modules/conv \
					modules/conv/float \
					modules/dct \
					modules/dct/float \
					modules/iir \
					modules/iir/biquad \
					modules/fir \
					modules/fir/float \
					modules/fir/fixed \
					modules/kalman/ekf/common \
					modules/kalman/ekf_imu13states
					
COMPONENT_PRIV_INCLUDEDIRS := 	modules/dotprod/float \
								modules/dotprod/fixed \
								modules/common/private_include 
					
