#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := fft2r

# This line has to be included into the make file
# to include components that are located somewhere 
# but not in "component" directory

EXTRA_COMPONENT_DIRS := $(realpath ../..)
EXCLUDE_COMPONENTS := test

include $(IDF_PATH)/make/project.mk

